In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np
# data temizlenir
# sonra model, linear regression


# System: 
# 170theta1 + 25theta2 + theta3 = 7
# 180theta1 + 30theta2 + theta3 = 8
# 200theta1 + 35theta2 + theta3 = 12

X = np.array([
    [170, 25, 1],
    [180, 30, 1],
    [200, 35, 1]
])
y = np.array([7, 8, 12])

theta = np.linalg.pinv(X) @ y
theta

array([  0.3,  -0.4, -34. ])

In [7]:
import matplotlib.pyplot as plt
rng = np.random.default_rng(seed=123)
m = 2000
boylar = rng.normal(loc=175,scale=10,size=(m,1))
boylar
yashlar = rng.uniform(low=18, high=65,size=(m,1))
yashlar
maashlar = rng.gamma(shape=3.5,scale=2,size=(m,1))

# plt.hist(boylar,bins=50)

In [15]:
from sklearn.preprocessing import add_dummy_feature
# X = np.hstack([boylar,yashlar,np.ones(shape=(m,1))])
X = np.hstack([boylar/100,yashlar/100])
y = maashlar.copy() / 10
X_b = add_dummy_feature(X)
X_b

array([[1.        , 1.65108786, 0.54917037],
       [1.        , 1.71322133, 0.57575708],
       [1.        , 1.87879253, 0.43439939],
       ...,
       [1.        , 1.61721291, 0.64432248],
       [1.        , 1.87379982, 0.53938548],
       [1.        , 1.87188795, 0.37919932]], shape=(2000, 3))

In [20]:
# rng.normal(loc=0,scale=1,size=(3,1))
theta = rng.standard_normal(size=(3,1))
eta = 0.1
m = len(X_b)

n_epochs = 1000000
for i in range(n_epochs):
    gradient = 1/m * X_b.T @ (X_b @ theta - y)
    theta = theta - eta*gradient

theta

array([[6.66968741],
       [0.03866652],
       [0.75095004]])

In [19]:
lr = LinearRegression()
lr.fit(X,y)
lr.coef_,lr.intercept_

(array([[0.03866652, 0.75095004]]), array([6.66968741]))